#!/usr/bin/env bash
# =============================================================================
#  mbx_classifier_run.sh
#  Run the full taxonomic classification pipeline using GG2 + QIIME2
#
#  Compatible with bash 3.2+ (macOS default shell)
#
#  Reads all parameters from 5_classifier_working_dir/mbx_classifier_run_info.txt
#  (generated by mbx_classifier_arranger.sh) — no manual parameter entry needed.
#
#  STEPS:
#    1  Parse mbx_classifier_run_info.txt
#    2  qiime feature-classifier extract-reads   → gg2_extracted_reads.qza
#         (auto-SKIPPED when CLASSIFIER_MODE=full-length OR when
#          CLASSIFIER_SOURCE=zenodo|cached)
#    3  qiime feature-classifier fit-classifier-naive-bayes
#         → gg2_trained_classifier.qza               (region-specific mode)
#         → gg2_full_length_trained_classifier.qza   (full-length mode)
#         (auto-SKIPPED when CLASSIFIER_SOURCE=zenodo|cached — the .qza was
#          downloaded pre-trained from https://zenodo.org/records/20021035)
#    4  qiime feature-classifier classify-sklearn → taxonomy.qza
#         (if it fails AND CLASSIFIER_SOURCE=zenodo, the downloaded file is
#          deleted and we automatically fall back to local training + retry)
#    5  qiime metadata tabulate                  → taxonomy.qzv
#
#  CLASSIFIER MODES (auto-selected by mbx_classifier_arranger.sh):
#    region-specific  primers known → V-region extracted from GG2 → train on it
#    full-length      no primers     → train Naive-Bayes on the full GG2 backbone
#
#  CLASSIFIER SOURCE (auto-selected by mbx_classifier_arranger.sh):
#    zenodo           pre-trained classifier downloaded + sha256-verified
#    cached           previously produced classifier reused
#    local-training   classifier will be trained on the fly here
#
#  REUSE LOGIC (idempotent — safe to re-run):
#    • extracted_reads.qza already exists   → skip Step 2
#    • trained_classifier.qza already exists → skip Step 3
#    • taxonomy.qza already exists           → skip Step 4
#    Reusable files (steps 2-3) live in 5_classifier_working_dir/
#    Final outputs (steps 4-5) live in 6_classifier_taxonomy/
#
#  OUTPUT STRUCTURE:
#    mbX_pro_outputs_<timestamp>/
#    ├── 5_classifier_working_dir/
#    │   ├── gg2_extracted_reads.qza        (reusable across projects)
#    │   └── gg2_trained_classifier.qza     (reusable across projects)
#    └── 6_classifier_taxonomy/
#        ├── taxonomy.qza
#        └── taxonomy.qzv
# =============================================================================

set -euo pipefail

# ── Helpers ───────────────────────────────────────────────────────────────────
err() {
  echo "" >&2
  echo "╔══════════════════════════════════════════════════════════════╗" >&2
  echo "║  ERROR                                                       ║" >&2
  echo "╚══════════════════════════════════════════════════════════════╝" >&2
  echo "[ERROR] $*" >&2
  echo "" >&2
  exit 1
}
warn()    { echo "[WARN]  $*" >&2; }
info()    { echo "[INFO]  $*"; }
ok()      { echo "[OK]    $*"; }
skipped() { echo "[SKIP]  $* — already exists, skipping."; }
step() {
  echo ""
  echo "┌─────────────────────────────────────────────────────────────────"
  echo "│  Step $*"
  echo "└─────────────────────────────────────────────────────────────────"
}
sep()     { echo "────────────────────────────────────────────────────────────────"; }
timer_start() { _T0="$(date +%s)"; }
timer_end()   {
  local _T1; _T1="$(date +%s)"
  local _S=$(( _T1 - _T0 ))
  printf "[TIME]  %dm %02ds\n" $(( _S/60 )) $(( _S%60 ))
}

_abspath() {
  if [[ -d "$1" ]]; then cd "$1" && pwd
  elif [[ -f "$1" ]]; then echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
  else return 1; fi
}

# Read a key from mbx_classifier_run_info.txt (handles paths containing =)
_read_key() {
  local key="$1" file="$2"
  grep "^${key}=" "$file" | cut -d= -f2-
}

# ── Usage ─────────────────────────────────────────────────────────────────────
usage() {
  cat <<'EOF'

mbx_classifier_run.sh — Run GG2 taxonomic classification (extract → train → classify)

USAGE:
  mbx_classifier_run.sh <mbX_pro_outputs_dir> [OPTIONS]

DESCRIPTION:
  Reads all parameters from:
    <mbX_pro_outputs_dir>/5_classifier_working_dir/mbx_classifier_run_info.txt

  Runs three QIIME2 steps in sequence:
    Step 2  extract-reads           trims GG2 to your amplicon region (~5–20 min)
    Step 3  fit-classifier          trains the Naive Bayes model   (~20–60 min)
    Step 4  classify-sklearn        assigns taxonomy to your ASVs  (~5–30 min)
    Step 5  metadata tabulate       makes taxonomy viewable

  Already-completed steps are automatically skipped (safe to re-run).
  Steps 2–3 outputs are saved in 5_classifier_working_dir/ for reuse.
  Final taxonomy outputs are saved in 6_classifier_taxonomy/.

OPTIONS:
  --force-extract      Re-run extract-reads even if output exists
  --force-train        Re-run fit-classifier even if output exists
  --force-classify     Re-run classify-sklearn even if output exists
  --skip-extract       Skip extract-reads (use existing or pre-built classifier)
  --classifier <path>  Provide a pre-built classifier .qza and skip steps 2–3
                       (e.g. the GG2 pre-built V4 classifier)
  --confidence <0-1>   Naive Bayes confidence threshold (default: 0.7)
  --dry-run            Print commands without executing
  -h, --help           Show this help and exit

EXAMPLES:
  # Standard run (reads everything from run_info.txt)
  mbx_classifier_run.sh /path/to/mbX_pro_outputs_20250422_143022

  # Use a pre-built classifier (skip extract + train)
  mbx_classifier_run.sh /path/to/mbX_pro_outputs_20250422_143022 \
    --classifier /path/to/gg2_2024.09_v4_classifier.qza

  # Re-run only the classification step
  mbx_classifier_run.sh /path/to/mbX_pro_outputs_20250422_143022 \
    --force-classify

  # Dry run to preview all commands
  mbx_classifier_run.sh /path/to/mbX_pro_outputs_20250422_143022 --dry-run

COMMON ERRORS:
  "qiime: command not found"
    → conda activate qiime2-amplicon-2025.4

  "No feature_classifier extract-reads command"
    → qiime info | grep feature-classifier
    → pip install q2-feature-classifier if missing

  "MemoryError during fit-classifier"
    → The NB training can need 8–16 GB RAM for GG2.
      Close other apps and retry.

  "Primers are None — cannot run extract-reads"
    → This is no longer fatal in v2.1+: the pipeline auto-falls back to
      FULL-LENGTH classifier mode (trains Naive-Bayes on the entire GG2
      backbone, no V-region extraction).  If you see this error you are
      probably running an older copy of mbx_classifier_arranger.sh; update
      both scripts and re-run.

  "taxonomy.qza already exists"
    → Use --force-classify to overwrite, or it was already successfully run.

EOF
  exit 0
}

# ── Parse arguments ───────────────────────────────────────────────────────────
MBX_OUT_DIR=""
FORCE_EXTRACT=false
FORCE_TRAIN=false
FORCE_CLASSIFY=false
SKIP_EXTRACT=false
EXTERNAL_CLASSIFIER=""
CONFIDENCE="0.7"
DRY_RUN=false

[[ $# -eq 0 ]] && usage

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)          usage ;;
    --dry-run)          DRY_RUN=true;              shift ;;
    --force-extract)    FORCE_EXTRACT=true;         shift ;;
    --force-train)      FORCE_TRAIN=true;           shift ;;
    --force-classify)   FORCE_CLASSIFY=true;        shift ;;
    --skip-extract)     SKIP_EXTRACT=true;          shift ;;
    --classifier)       EXTERNAL_CLASSIFIER="${2:?Missing value for --classifier}"; shift 2 ;;
    --confidence)       CONFIDENCE="${2:?Missing value for --confidence}"; shift 2 ;;
    -*)  err "Unknown option: '${1}'  —  run with --help for usage." ;;
    *)
      if [[ -z "$MBX_OUT_DIR" ]]; then MBX_OUT_DIR="$1"; shift
      else err "Unexpected extra argument: '${1}'"; fi ;;
  esac
done

[[ -z "$MBX_OUT_DIR" ]] && err "No mbX_pro_outputs directory provided.  Run with --help."
[[ -d "$MBX_OUT_DIR" ]] || err "Directory does not exist: '${MBX_OUT_DIR}'"
MBX_OUT_DIR="$(_abspath "$MBX_OUT_DIR")"

# ── Verify QIIME2 ─────────────────────────────────────────────────────────────
command -v qiime &>/dev/null || err "qiime not found.
  → conda activate qiime2-amplicon-2025.4"

# ── Auto-detect CPU cores ──────────────────────────────────────────────────────
if command -v nproc &>/dev/null; then
  N_JOBS="$(nproc)"
elif command -v sysctl &>/dev/null; then
  N_JOBS="$(sysctl -n hw.logicalcpu 2>/dev/null || echo 1)"
else
  N_JOBS=1
fi

# ─────────────────────────────────────────────────────────────────────────────
step "1/5 — Parse mbx_classifier_run_info.txt"
# ─────────────────────────────────────────────────────────────────────────────

RUN_INFO="${MBX_OUT_DIR}/5_classifier_working_dir/mbx_classifier_run_info.txt"

[[ -f "$RUN_INFO" ]] || err "mbx_classifier_run_info.txt not found at:
  $RUN_INFO
  → Run mbx_classifier_arranger.sh first."

# ── Read all parameters from the info file ─────────────────────────────────
GG2_FNA_QZA="$(_read_key   "GG2_FULL_LENGTH_FNA_QZA"  "$RUN_INFO")"
GG2_TAX_QZA="$(_read_key   "GG2_TAXONOMY_QZA"          "$RUN_INFO")"
REP_SEQS_QZA="$(_read_key  "REPRESENTATIVE_SEQUENCES_QZA" "$RUN_INFO")"
FWD_PRIMER="$(_read_key    "FORWARD_PRIMER_SEQUENCE"   "$RUN_INFO")"
REV_PRIMER="$(_read_key    "REVERSE_PRIMER_SEQUENCE"   "$RUN_INFO")"
MIN_LEN="$(_read_key       "MIN_ASV_LENGTH"             "$RUN_INFO" | grep -oE '[0-9]+'  || true)"
MAX_LEN="$(_read_key       "MAX_ASV_LENGTH"             "$RUN_INFO" | grep -oE '[0-9]+'  || true)"
EXTRACTED_QZA="$(_read_key "EXTRACTED_READS_QZA"        "$RUN_INFO")"
TRAINED_QZA="$(_read_key   "TRAINED_CLASSIFIER_QZA"     "$RUN_INFO")"
TARGET_REGION="$(_read_key "TARGET_REGION"              "$RUN_INFO")"
GG2_VER="$(_read_key       "GG2_VERSION"                "$RUN_INFO")"
CLASSIFIER_MODE="$(_read_key "CLASSIFIER_MODE"          "$RUN_INFO")"
[[ -z "$CLASSIFIER_MODE" ]] && CLASSIFIER_MODE="region-specific"
CLASSIFIER_SOURCE="$(_read_key "CLASSIFIER_SOURCE"      "$RUN_INFO")"
[[ -z "$CLASSIFIER_SOURCE" ]] && CLASSIFIER_SOURCE="local-training"
ZENODO_FILENAME="$(_read_key "ZENODO_FILENAME"          "$RUN_INFO")"
ZENODO_SHA256_EXPECTED="$(_read_key "ZENODO_SHA256_EXPECTED" "$RUN_INFO")"

# Validate critical inputs
[[ -z "$REP_SEQS_QZA"  ]] && err "REPRESENTATIVE_SEQUENCES_QZA missing from run_info.txt"
[[ -z "$TRAINED_QZA"   ]] && err "TRAINED_CLASSIFIER_QZA missing from run_info.txt"
[[ -f "$REP_SEQS_QZA" ]] || err "representative_sequences.qza not found: $REP_SEQS_QZA
  → Run mbx_dada2_run.sh first."

# GG2 reference files are only needed when we are training locally.
# When CLASSIFIER_SOURCE=zenodo|cached we already have the trained .qza.
if [[ "$CLASSIFIER_SOURCE" == "local-training" ]]; then
  [[ -z "$GG2_FNA_QZA" ]] && err "GG2_FULL_LENGTH_FNA_QZA missing from run_info.txt"
  [[ -z "$GG2_TAX_QZA" ]] && err "GG2_TAXONOMY_QZA missing from run_info.txt"
  if [[ "$CLASSIFIER_MODE" == "region-specific" ]]; then
    [[ -z "$EXTRACTED_QZA" ]] && err "EXTRACTED_READS_QZA missing from run_info.txt (region-specific mode)"
  fi
  [[ -f "$GG2_FNA_QZA" ]] || err "GG2 sequences file not found: $GG2_FNA_QZA
  → Re-run mbx_classifier_arranger.sh to download it."
  [[ -f "$GG2_TAX_QZA" ]] || err "GG2 taxonomy file not found: $GG2_TAX_QZA
  → Re-run mbx_classifier_arranger.sh to download it."
fi

# ── Handle external pre-built classifier ──────────────────────────────────────
USING_EXTERNAL_CLASSIFIER=false
if [[ -n "$EXTERNAL_CLASSIFIER" ]]; then
  [[ -f "$EXTERNAL_CLASSIFIER" ]] || err "Pre-built classifier not found: $EXTERNAL_CLASSIFIER"
  TRAINED_QZA="$(_abspath "$EXTERNAL_CLASSIFIER")"
  SKIP_EXTRACT=true
  USING_EXTERNAL_CLASSIFIER=true
  info "Using external pre-built classifier: $TRAINED_QZA"
  info "Steps 2 and 3 will be skipped."
fi

# ── Detect if primers are usable ──────────────────────────────────────────────
PRIMERS_OK=false
if [[ "$FWD_PRIMER" != "None" && "$REV_PRIMER" != "None" && \
      -n "$FWD_PRIMER" && -n "$REV_PRIMER" ]]; then
  PRIMERS_OK=true
fi

# ── Honour CLASSIFIER_MODE / CLASSIFIER_SOURCE from run_info.txt ─────────────
# Two independent decisions made by the arranger:
#   CLASSIFIER_MODE   : region-specific vs full-length
#   CLASSIFIER_SOURCE : local-training vs zenodo vs cached
#
# When CLASSIFIER_SOURCE == zenodo|cached the trained .qza already exists at
# $TRAINED_QZA — we skip BOTH extract-reads (Step 2) AND fit-classifier
# (Step 3) and jump straight to classify-sklearn (Step 4).
SKIP_TRAIN=false
if [[ "$CLASSIFIER_SOURCE" == "zenodo" || "$CLASSIFIER_SOURCE" == "cached" ]] \
   && ! $USING_EXTERNAL_CLASSIFIER; then
  SKIP_EXTRACT=true
  SKIP_TRAIN=true
  ok "═══════════════════════════════════════════════════════════════════"
  ok "  CLASSIFIER_SOURCE=$CLASSIFIER_SOURCE — using the existing pre-trained .qza."
  ok "  Step 2 (extract-reads)              -> SKIPPED."
  ok "  Step 3 (fit-classifier-naive-bayes) -> SKIPPED."
  ok "  Jumping straight to Step 4 (classify-sklearn)."
  if [[ "$CLASSIFIER_SOURCE" == "zenodo" ]]; then
    ok "  Source: $ZENODO_FILENAME"
    ok "  Time saved vs local training: ~30-90 minutes."
  fi
  ok "═══════════════════════════════════════════════════════════════════"
elif [[ "$CLASSIFIER_MODE" == "full-length" ]] && ! $USING_EXTERNAL_CLASSIFIER; then
  SKIP_EXTRACT=true
  warn "═══════════════════════════════════════════════════════════════════"
  warn "  CLASSIFIER_MODE=full-length — primers were unavailable."
  warn "  Step 2 (extract-reads) will be SKIPPED."
  warn "  Step 3 (fit-classifier-naive-bayes) will train on the FULL GG2"
  warn "  backbone (no V-region trimming).  This takes 30-90 minutes the"
  warn "  first time and uses 8-16 GB RAM, but the trained classifier is"
  warn "  reusable for any future project (regardless of primer set)."
  warn "═══════════════════════════════════════════════════════════════════"
fi

# Only error if we are *expected* to extract but cannot (region-specific mode +
# no primers + no external classifier).  This should not happen with a properly
# generated run_info.txt but we guard against stale info files.
if [[ "$CLASSIFIER_MODE" == "region-specific" ]] \
   && ! $PRIMERS_OK && ! $SKIP_EXTRACT && ! $USING_EXTERNAL_CLASSIFIER; then
  err "CLASSIFIER_MODE=region-specific but primers are None.
  This run_info.txt is inconsistent — re-run mbx_classifier_arranger.sh to
  refresh it (it will auto-detect the missing primers and switch to
  CLASSIFIER_MODE=full-length).
  Or pass --classifier /path/to/prebuilt_classifier.qza to skip steps 2-3."
fi

# ── Validate lengths ──────────────────────────────────────────────────────────
if [[ -z "$MIN_LEN" || -z "$MAX_LEN" ]]; then
  warn "Min/max ASV lengths could not be parsed. Falling back to safe defaults."
  MIN_LEN=100
  MAX_LEN=500
  warn "Using fallback: --p-min-length $MIN_LEN  --p-max-length $MAX_LEN"
fi

# ── Create output directory ───────────────────────────────────────────────────
TAXONOMY_DIR="${MBX_OUT_DIR}/6_classifier_taxonomy"
mkdir -p "$TAXONOMY_DIR" \
  || err "Could not create: $TAXONOMY_DIR — check permissions."

TAXONOMY_QZA="${TAXONOMY_DIR}/taxonomy.qza"
TAXONOMY_QZV="${TAXONOMY_DIR}/taxonomy.qzv"

# ── Print run summary ─────────────────────────────────────────────────────────
sep
info "mbX_pro_outputs dir  : $MBX_OUT_DIR"
info "GG2 version          : $GG2_VER"
info "Classifier mode      : $CLASSIFIER_MODE"
info "Classifier source    : $CLASSIFIER_SOURCE"
[[ -n "$ZENODO_FILENAME" && "$ZENODO_FILENAME" != "(none)" ]] \
  && info "Zenodo file          : $ZENODO_FILENAME"
info "Target region        : $TARGET_REGION"
info "Forward primer       : $FWD_PRIMER"
info "Reverse primer       : $REV_PRIMER"
info "Min ASV length       : $MIN_LEN bp"
info "Max ASV length       : $MAX_LEN bp"
info "CPU cores            : $N_JOBS"
info "Confidence threshold : $CONFIDENCE"
info "Output directory     : $TAXONOMY_DIR"
$DRY_RUN && warn "DRY-RUN — commands will be printed but NOT executed."
sep

# ── Dry-run helper ─────────────────────────────────────────────────────────────
run_cmd() {
  # Print command formatted with line-continuation for readability
  echo ""
  echo "  \$ $(echo "$@" | sed 's/ --/\\ \n    --/g')"
  echo ""
  if ! $DRY_RUN; then
    "$@" || err "Command failed: $1
  → Check the QIIME2 output above for details.
  → Re-run with --dry-run to inspect the exact command."
  fi
}

# ─────────────────────────────────────────────────────────────────────────────
step "2/5 — Extract amplicon-region reads from GG2 reference"
# ─────────────────────────────────────────────────────────────────────────────
# Trims full-length GG2 sequences to your specific primer-amplified V-region.
# This is the single most important step for classification accuracy.
# Output lives in 5_classifier_working_dir/ and is reusable across projects.

if $SKIP_EXTRACT || $USING_EXTERNAL_CLASSIFIER; then
  skipped "extract-reads (--skip-extract or external classifier provided)"
elif [[ -f "$EXTRACTED_QZA" ]] && ! $FORCE_EXTRACT; then
  skipped "extract-reads output already exists: $(basename "$EXTRACTED_QZA")"
  info "  Use --force-extract to re-run this step."
else
  info "Trimming GG2 reference to region: $TARGET_REGION"
  info "This step typically takes 5–20 minutes..."
  timer_start
  run_cmd qiime feature-classifier extract-reads \
    --i-sequences  "$GG2_FNA_QZA" \
    --p-f-primer   "$FWD_PRIMER" \
    --p-r-primer   "$REV_PRIMER" \
    --p-min-length "$MIN_LEN" \
    --p-max-length "$MAX_LEN" \
    --p-n-jobs     "$N_JOBS" \
    --o-reads      "$EXTRACTED_QZA"
  timer_end
  $DRY_RUN || ok "Extracted reads → $EXTRACTED_QZA"
fi

# ─────────────────────────────────────────────────────────────────────────────
step "3/5 — Train Naive Bayes classifier on extracted region"
# ─────────────────────────────────────────────────────────────────────────────
# Trains the NB model on the region-specific reference sequences.
# This can take 20–60 minutes and ~8–16 GB RAM for GG2.
# Output lives in 5_classifier_working_dir/ and is REUSABLE:
#   same primers + same GG2 version = same classifier. Train once, reuse many.

if $USING_EXTERNAL_CLASSIFIER; then
  skipped "fit-classifier (external classifier provided)"
elif $SKIP_TRAIN; then
  skipped "fit-classifier (CLASSIFIER_SOURCE=$CLASSIFIER_SOURCE — already trained)"
elif [[ -f "$TRAINED_QZA" ]] && ! $FORCE_TRAIN; then
  skipped "fit-classifier output already exists: $(basename "$TRAINED_QZA")"
  info "  Use --force-train to re-run this step."
else
  # Decide which reference to train on, based on classifier mode.
  if [[ "$CLASSIFIER_MODE" == "full-length" ]]; then
    REF_QZA="$GG2_FNA_QZA"
    info "Training Naive-Bayes on FULL GG2 backbone (full-length mode)."
    info "Expected runtime: 30-90 minutes.  Memory: 8-16 GB."
    info "Output classifier: $(basename "$TRAINED_QZA")"
    info "(This is automatic because primers were not detected.)"
  else
    REF_QZA="$EXTRACTED_QZA"
    [[ -f "$REF_QZA" ]] || err "Extracted reads not found: $REF_QZA
  → Run Step 2 first (or re-run without --skip-extract)."
    info "Training Naive-Bayes on V-region extract (region-specific mode)."
    info "Expected runtime: 20-60 minutes.  Memory: 8-16 GB."
  fi
  timer_start
  run_cmd qiime feature-classifier fit-classifier-naive-bayes \
    --i-reference-reads    "$REF_QZA" \
    --i-reference-taxonomy "$GG2_TAX_QZA" \
    --o-classifier         "$TRAINED_QZA"
  timer_end
  $DRY_RUN || ok "Trained classifier → $TRAINED_QZA"
  $DRY_RUN || info "This classifier is reusable for future projects with the same GG2 version."
  if [[ "$CLASSIFIER_MODE" == "full-length" ]]; then
    $DRY_RUN || info "Full-length mode: usable across ANY primer set / V-region."
  fi
fi

# ─────────────────────────────────────────────────────────────────────────────
step "4/5 — Classify ASVs with trained classifier"
# ─────────────────────────────────────────────────────────────────────────────
# Assigns taxonomy to your representative sequences using the trained NB model.
# --p-confidence 0.7 is the QIIME2 default:
#   lower  → more assignments, more potential false positives
#   higher → fewer assignments, higher confidence

# Helper: actually run classify-sklearn.  Returns exit code.
_run_classify_sklearn() {
  qiime feature-classifier classify-sklearn \
    --i-classifier     "$TRAINED_QZA" \
    --i-reads          "$REP_SEQS_QZA" \
    --p-n-jobs         "$N_JOBS" \
    --p-confidence     "$CONFIDENCE" \
    --o-classification "$TAXONOMY_QZA"
}

if [[ -f "$TAXONOMY_QZA" ]] && ! $FORCE_CLASSIFY; then
  skipped "taxonomy.qza already exists: $TAXONOMY_QZA"
  info "  Use --force-classify to overwrite."
else
  if ! $DRY_RUN; then
    [[ -f "$TRAINED_QZA" ]] || err "Trained classifier not found: $TRAINED_QZA
  → Run Step 3 first, or provide a pre-built classifier with --classifier."
  fi
  info "Classifying ASVs using $N_JOBS CPU core(s)..."
  info "Confidence threshold: $CONFIDENCE"
  if $DRY_RUN; then
    run_cmd qiime feature-classifier classify-sklearn \
      --i-classifier     "$TRAINED_QZA" \
      --i-reads          "$REP_SEQS_QZA" \
      --p-n-jobs         "$N_JOBS" \
      --p-confidence     "$CONFIDENCE" \
      --o-classification "$TAXONOMY_QZA"
  else
    timer_start
    set +e
    _run_classify_sklearn 2>&1
    CLF_RC=$?
    set -e
    timer_end

    if [[ "$CLF_RC" -ne 0 ]]; then
      # ── Zenodo fall-back logic ─────────────────────────────────────────────
      # If the classifier we just tried to use was downloaded from Zenodo and
      # classify-sklearn rejected it (most likely cause: a sklearn pickle
      # incompatibility we did not anticipate), we delete it and retrain
      # locally on the spot.  The pipeline ALWAYS continues.
      if [[ "$CLASSIFIER_SOURCE" == "zenodo" ]]; then
        warn "═══════════════════════════════════════════════════════════════════"
        warn "  classify-sklearn failed with the Zenodo pre-trained classifier"
        warn "  ($CLF_RC).  This is the documented fall-back path."
        warn "  → Deleting the Zenodo .qza and retraining on the GG2 backbone."
        warn "═══════════════════════════════════════════════════════════════════"
        rm -f "$TRAINED_QZA"

        # Make sure GG2 reference files are available for retraining.
        if [[ ! -f "$GG2_FNA_QZA" || ! -f "$GG2_TAX_QZA" ]]; then
          warn "GG2 reference files were skipped earlier (Zenodo fast-path)."
          warn "Re-running mbx_classifier_arranger.sh --skip-zenodo to fetch them."
          if command -v mbx_classifier_arranger.sh &>/dev/null; then
            mbx_classifier_arranger.sh "$MBX_OUT_DIR" --skip-zenodo \
              || err "Could not re-fetch GG2 reference files. Please run:
  mbx_classifier_arranger.sh '$MBX_OUT_DIR' --skip-zenodo
manually, then re-run this script."
            # Re-read paths in case the arranger updated them
            GG2_FNA_QZA="$(_read_key "GG2_FULL_LENGTH_FNA_QZA" "$RUN_INFO")"
            GG2_TAX_QZA="$(_read_key "GG2_TAXONOMY_QZA"        "$RUN_INFO")"
          else
            err "mbx_classifier_arranger.sh not on PATH; cannot self-heal.
  → Manually download the GG2 backbone and re-run this script."
          fi
        fi

        info "Training Naive-Bayes locally on the FULL GG2 backbone..."
        info "Expected runtime: 30-90 minutes."
        timer_start
        qiime feature-classifier fit-classifier-naive-bayes \
          --i-reference-reads    "$GG2_FNA_QZA" \
          --i-reference-taxonomy "$GG2_TAX_QZA" \
          --o-classifier         "$TRAINED_QZA" \
          || err "Local training fall-back also failed.  Inspect the log above
  for the underlying QIIME2 error.  This is the last resort — please
  open an issue with the full output."
        timer_end
        ok "Local training complete -> $TRAINED_QZA"

        # Update CLASSIFIER_SOURCE in the run info file for the report.
        if grep -q '^CLASSIFIER_SOURCE=' "$RUN_INFO"; then
          # Use a portable in-place edit (no GNU-only sed -i)
          _tmp="${RUN_INFO}.tmp.$$"
          sed 's|^CLASSIFIER_SOURCE=.*|CLASSIFIER_SOURCE=local-training-fallback|' \
              "$RUN_INFO" > "$_tmp" && mv "$_tmp" "$RUN_INFO"
        fi
        CLASSIFIER_SOURCE="local-training-fallback"

        info "Retrying classify-sklearn with the locally-trained classifier..."
        timer_start
        _run_classify_sklearn || err "classify-sklearn failed even with the
  freshly-trained local classifier.  Inspect the QIIME2 output above for the
  cause (commonly: insufficient RAM for the dataset size)."
        timer_end
      else
        err "classify-sklearn failed (exit $CLF_RC).
  → Inspect the QIIME2 output above for the cause."
      fi
    fi
    ok "Taxonomy → $TAXONOMY_QZA"
  fi
fi

# ─────────────────────────────────────────────────────────────────────────────
step "5/5 — Tabulate taxonomy → taxonomy.qzv"
# ─────────────────────────────────────────────────────────────────────────────

if [[ -f "$TAXONOMY_QZV" ]] && ! $FORCE_CLASSIFY; then
  skipped "taxonomy.qzv already exists."
else
  [[ -f "$TAXONOMY_QZA" ]] || { $DRY_RUN || err "taxonomy.qza not found — Step 4 must complete first."; }
  if ! $DRY_RUN; then
    timer_start
    run_cmd qiime metadata tabulate \
      --m-input-file     "$TAXONOMY_QZA" \
      --o-visualization  "$TAXONOMY_QZV"
    timer_end
    ok "Taxonomy visualization → $TAXONOMY_QZV"
  else
    run_cmd qiime metadata tabulate \
      --m-input-file     "$TAXONOMY_QZA" \
      --o-visualization  "$TAXONOMY_QZV"
  fi
fi

# ── Final summary ─────────────────────────────────────────────────────────────
sep
if $DRY_RUN; then
  warn "Dry-run complete — no commands were executed."
else
  ok "All classification steps complete!"
fi
sep
echo ""
echo "  Output structure:"
echo "  $MBX_OUT_DIR/"
echo "  ├── 5_classifier_working_dir/"
if [[ "$CLASSIFIER_MODE" == "region-specific" ]]; then
  printf '  │   ├── %-42s  ← reusable (V-region trim)\n' "$(basename "$EXTRACTED_QZA")"
  printf '  │   └── %-42s  ← reusable (region-specific NB)\n' "$(basename "$TRAINED_QZA")"
else
  printf '  │   └── %-42s  ← reusable (full-length NB)\n' "$(basename "$TRAINED_QZA")"
fi
echo "  └── 6_classifier_taxonomy/"
echo "      ├── taxonomy.qza"
echo "      └── taxonomy.qzv"
echo ""
echo "  View taxonomy.qzv at: https://view.qiime2.org"
echo ""
echo "  ── Suggested next steps ─────────────────────────────────────────"
FEATURE_TABLE="${MBX_OUT_DIR}/4_dada2_outputs/feature_table.qza"
echo ""
echo "  Taxonomy bar plot (requires metadata.txt):"
printf '    qiime taxa barplot \\\n'
printf '      --i-table      %s \\\n'    "$FEATURE_TABLE"
printf '      --i-taxonomy   %s \\\n'    "$TAXONOMY_QZA"
printf '      --m-metadata-file /path/to/metadata.txt \\\n'
printf '      --o-visualization %s/taxa_barplot.qzv\n' "$TAXONOMY_DIR"
echo ""
echo "  Filter out mitochondria and chloroplasts:"
printf '    qiime taxa filter-table \\\n'
printf '      --i-table      %s \\\n'    "$FEATURE_TABLE"
printf '      --i-taxonomy   %s \\\n'    "$TAXONOMY_QZA"
printf "      --p-exclude mitochondria,chloroplast \\\\\n"
printf '      --o-filtered-table %s/feature_table_filtered.qza\n' "$TAXONOMY_DIR"
echo ""
